### ISSUE TITLE
Before final release : improve design details

### ISSUE THREAD

**Issue by mgpiegette** [scg-unibe-ch/ese2016-team6#117]
- center ads in My Bookmarks & My ads
- My schedule : add a title and separate better the two arrays
- alerts : separate better "create new alerts" & "your active alerts"

**Comment by mgpiegette** [comment]
Add title to Schedule done

**Comment by mgpiegette** [comment]
Ads & Bookmarks centered (change the position of blocks ?)

**Comment by VHaftka** [comment]
now those are because it implemented for a bigger screen than yours -> press cmd and -, then it should change...
