### ISSUE TITLE
Search : still have a problem with "Biel;Bienne"

### ISSUE THREAD

**Issue by mgpiegette** [scg-unibe-ch/ese2016-team6#118]

**Comment by mgpiegette** [comment]
Now fixed to Biel/Bienne but search doesn't work "please choose a city from the list"

**Comment by mgpiegette** [comment]
Same problem with AlertsForm & PlaceAdForm

**Comment by mgpiegette** [comment]
Same problem with Genève / Genf

**Comment by PIndermuehle** [comment]
should be fixed now
