### ISSUE TITLE
ads of premium user are a bit higher in the result list

### ISSUE THREAD

**Issue by VHaftka** [scg-unibe-ch/ese2016-team6#18]
if a user search for a adds the ads of the premium user are at the beginning, even if they do not perfectly match the search criteria

closed if you search for something and then you first see the ads of the premium users

**Comment by VHaftka** [comment]
Now you get the premiumusers Ads even if they dont match, but you they are not in the first place -> still have to fix that

**Comment by mgpiegette** [comment]
#24

**Comment by VHaftka** [comment]
Premium users ads are in the first place, but only if they dont match more then 5 attributes.
