### ISSUE TITLE
Remove room&studio

### ISSUE THREAD

**Issue by mgpiegette** [scg-unibe-ch/ese2016-team6#19]
the difference between room & studio is useless now, considering that we added "for rent" & "for sale"

**Comment by mgpiegette** [comment]
all concerning rooms & studios has been put into commentaries ONLY IN JSP PAGES
it hasn't been completely removed because it could be useful
if you consider it is not, please delete it

**Comment by PIndermuehle** [comment]
I will help comment out the room/studio displays. It seems some of your changes have been reverted
