### ISSUE TITLE
normal users get a weekly summary with the new adds by email

### ISSUE THREAD

**Issue by VHaftka** [scg-unibe-ch/ese2016-team6#3]

**Comment by VHaftka** [comment]
An email with a short summary of every Add

Close when the user get an email as descript every week (for testing every minute)

**Comment by VHaftka** [comment]
The Normal user get an email every week (every minute for testing) with all ads that have been made and a short description and the corresponding link of the ad.

**Comment by mgpiegette** [comment]
#24
