### ISSUE TITLE
Bug: Editing an ad fails

### ISSUE THREAD

**Issue by meggima** [scg-unibe-ch/ese2016-team6#34]
**Short description**
When a user wants to edit an ad, he gets a NullReferenceException.

**Affected version**
Release 2.0

**Steps to reproduce:**

1. Login with ese@unibe.ch
2. Go to My Rooms
3. Select the ad "Cheap studio in Bern!"
4. Click Edit Ad
5. Don't change anything
6. Click "Submit"
7. Validation error at "Number of rooms" shows up
8. Enter a number for the field
9. Click "Submit"
10. A NullReferenceException occurs

**Comment by berzahnd** [comment]
various commits fixed this bug
