### ISSUE TITLE
Bug: Some citys can't be selected

### ISSUE THREAD

**Issue by meggima** [scg-unibe-ch/ese2016-team6#35]
**Short description**
Some citys can't be selected when placing an ad. For example: Biel/Bienne

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as ese@unibe.ch
2. Go to http://localhost:8080/profile/editAd?id=6
3. Click "Submit"
4. Validation error shows up

**Cause**
The regex on the placeAdForm.city (line 23) allows just normal characters for city names.

**Comment by berzahnd** [comment]
fixed with commit 22a3949edbbec7cc4c3d71130618c980c5832987
