### ISSUE TITLE
Bug: Place Ad form is prefilled with old values

### ISSUE THREAD

**Issue by meggima** [scg-unibe-ch/ese2016-team6#37]
**Short description**
If the user edits an ad and gets validation errors and afterwards tries to place a new ad, the old values from the previously edited ad are shown in the form.

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as user ese@unibe.ch
2. Edit one of his ads such that you get a validation error
3. Click on place ad in the main menu
4. The form is prefilled with the values from the previously edited ad

**Comment by VHaftka** [comment]
seems to be done with the newer version
