### ISSUE TITLE
Bug: Place ad values for auction date get lost

### ISSUE THREAD

**Issue by meggima** [scg-unibe-ch/ese2016-team6#38]
**Short description**
If the user wants to place an ad with auction and gets validation errors, the values for Deadline get lost.

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as ese@unibe.ch
2. Place an ad
3. Fill in some values, but "Monthly rental charges" blank
4. Fill in values for the auction
5. Click "Submit"
6. Validation errors show up
7. Values for deadline are lost
8. Strange validation message is shown for "Monthly rental charges"

**Comment by PIndermuehle** [comment]
should be fixed now
