### ISSUE TITLE
Bug: Inbox text in navigation is not displayed

### ISSUE THREAD

**Issue by meggima** [scg-unibe-ch/ese2016-team6#39]
**Short description**
The link inbox in the navigation has no text, but is shown as blank line and clickable.

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as ese@unibe.ch
2. Click on the user image in the navigation
3. The inbox link is shown as blank

**Comment by VHaftka** [comment]
seems to be fixed in the newest version
