### ISSUE TITLE
Bug: User can edit other users ad

### ISSUE THREAD

**Issue by meggima** [scg-unibe-ch/ese2016-team6#40]
**Short description**
A user can edit the ads of other users by manipulating the ad id in the url

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as ese@unibe.ch
2. Place an ad (**important**: the values should be filled in in such a way, that the edit bug #34 doesn't interfere, for example the "number of rooms" field must be set, so editing must be possible)
3. Note the id of the create ad
4. Log out
5. Log in as jane@doe.com
6. Got to My Rooms
7. Select one room
8. Click on "Edit ad"
9. Change the id in the url to the noted id from step 3
10. Change some values
11. Click on submit
12. The ad has been edited even though it doesn't belong to the logged in user

**Comment by berzahnd** [comment]
Doing this now results in a forbidden error
