### ISSUE TITLE
Bug: Not possible to send new messages on 'messages' page

### ISSUE THREAD

**Issue by rongshabing** [scg-unibe-ch/ese2016-team6#42]
#### Short description
The button for "new" message on the messages page does not work and no field for a new message pops up.

#### Affected version
Release 2.0

#### Steps to reproduce

1. Log in as ese@unibe.ch
2. Click on the user image in the navigation
3. Click on 'Messages'
4. On the messages page, click on "New"
5. Nothing happens

**Comment by VHaftka** [comment]
seems to be fixed in the newest version
