### ISSUE TITLE
Bug: Only newest received message can be displayed

### ISSUE THREAD

**Issue by rongshabing** [scg-unibe-ch/ese2016-team6#43]
#### Short description
When I want to look at the different received and sent messages, only the newest received one is displayed and i can't look at the different messages.

#### Affected version
Release 2.0

#### Steps to reproduce

1. Log in as jane@doe.com 
2. Click on the user image in the navigation
3. Click on 'Messages'
4. On the messages page, click on any message in the message table
5. The newest received message is displayed, whether i click on that one or another
6. Click on the "sent" button
7. The table changes to all the messages that I have sent
8. Click on any message in the sent message table
9. The same newly received message is displayed instead of one of the sent table

**Comment by PIndermuehle** [comment]
seems to have been fixed already

**Comment by VHaftka** [comment]
is fixed in the newest version
