### ISSUE TITLE
Bug: Can choose negative number for Number of Rooms and Size in Alerts creation

### ISSUE THREAD

**Issue by rongshabing** [scg-unibe-ch/ese2016-team6#45]
#### Short description
When creating a new alert, one can choose a negative number for the number of rooms field, same for min and max of square meter size

#### Affected version
Release 2.0

#### Steps to reproduce

1. Log in as jane@doe.com 
2. Click on the user image in the navigation
3. Click on 'Alerts'
4. Create a new alert, with number of rooms '-6', min. square meters '-100', max square meters '-50'
5. Click on 'Subscribe'
6. The request is accepted and the Alerts table now says for min. Number of Rooms: "-6" and Size: "-100 - -50 Square Meters"

**Comment by VHaftka** [comment]
That part is working if the radiobuttons are working...
