### ISSUE TITLE
Bug: User can add visiting times with an invalid date

### ISSUE THREAD

**Issue by ytrehorn** [scg-unibe-ch/ese2016-team6#48]
**Short description**
User can add visiting times with invalid dates.

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as ese@unibe
2. Go to my properties and select a property, edit ad
3. Add random number for date of visiting time, for instance 23456789, with valid hours
4. Submit. The visiting time added will show as "from until"

**Comment by VHaftka** [comment]
seems you can't even add visiting time at the newest version

**Comment by PIndermuehle** [comment]
fixed this by making the input field readonly and adding a minDate to the datepicker
