### ISSUE TITLE
Bug: Delete 0 in Search for an ad results in java.lang.NumberFormatException

### ISSUE THREAD

**Issue by zaraa101** [scg-unibe-ch/ese2016-team6#50]
**Short description**
Search for an ad: When someone would delete the default 0 in Rooms(min): then the user gets a non informative java.lang.NumberFormatException message

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as jane@doe.com
2. Click on Search
3. Delete 0 in Rooms(min): 0 Rooms
4. Click on Search button

**Comment by VHaftka** [comment]
Added the default value for Number of Rooms to 1, you shout not get the Exception now
