### ISSUE TITLE
Bug: Search Mechanism fails

### ISSUE THREAD

**Issue by zaraa101** [scg-unibe-ch/ese2016-team6#51]
**Short description**
Search for an ad: When searching only for ads that are for sale, in the results site, there appear flats that are for rent

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as jane@doe.com
2. Click on Search
3. Click on checkbox For Sale, City= 3095 Spiegel, Within radius(max)=5000 km, Price(max)=50000CHF
4. Click on Search button
5. See results, there are only ads, which are for rent

**Comment by PIndermuehle** [comment]
latest merge seems to have undone the fix

**Comment by PIndermuehle** [comment]
false alert. latest merge did not undo the fix, there is another bug with it

**Comment by PIndermuehle** [comment]
fixed
