### ISSUE TITLE
Bug: Search Form is always pre filled with old values from previous user

### ISSUE THREAD

**Issue by zaraa101** [scg-unibe-ch/ese2016-team6#52]
**Short description**
Search for an ad: When a user searches for example: For Rent, City = 8000-Zürich Within radius of(max)=5000 km, Price (max)=50000CHF, Rooms(min) = 0 Rooms, and then logs out. Another user signs in and clicks on search, the search form is pre filled with these old values from the previous user.

**Affected version**
Release 2.0

**Steps to reproduce**
1. Log in as jane@doe.com
2. Click on Search
3. checkbox For Rent, City = 8000-Zürich Within radius of(max)=5000 km, Price (max)=50000CHF, Rooms(min) = 0 Rooms
4. Click on Search button
5. logout
6. Log in as ese@unibe.ch
7. Click on Search

**Comment by VHaftka** [comment]
Now every time you click on the search button there is an unfilled form.
