### ISSUE TITLE
Bug: editing of user email address causes server error

### ISSUE THREAD

**Issue by lwuersch** [scg-unibe-ch/ese2016-team6#53]
**Short description**

A user can edit his own email address, which causes a server error. In addition, the user can edit his own status (normal or premium)

**Affected version**

Release 2.0

**Steps to reproduce**

1. Login as jane@doe.com
2. go to public profile -> edit profile 
3. If email address is changed, a server error is caused

**Comment by VHaftka** [comment]
Now you can change your email address.
