### ISSUE TITLE
Bug: new enquiries not displayed

### ISSUE THREAD

**Issue by lwuersch** [scg-unibe-ch/ese2016-team6#54]
**Short description**

Enquiries are not correctly sent to the receiver. When the button "Send enquiries to advertiser" is clicked, nothing happens.

**Affected version**

Release 2.0

**Steps to reproduce**

1. create new normal user and log in
2. Visit ad "Direkt am Quai: hübsches Studio" and click "Send enquiries to advertiser" (belongs  to ese@unibe.ch)
3. Log in as ese@unibe.ch
3. View Enquiries of ese@unibe.ch. No new Enquiries are registered there.

**Comment by PIndermuehle** [comment]
was tested on 22/11/2016.
enquiries are properly shown in the enquiries page after having been sent
