### ISSUE TITLE
Edit ad Crashes

### ISSUE THREAD

**Issue by PIndermuehle** [scg-unibe-ch/ese2016-team6#59]
login as ese@unibe.ch
clock editAd for the "direkt am quai" ad
do not change anything just submit with no changes.
result is a crash

**Comment by mgpiegette** [comment]
>javax.validation.UnexpectedTypeException: HV000030: No validator could be found for type: ch.unibe.ese.team6.model.KindOfDeal.

Probably just a matter of variables concerning sale/rent/auction etc.
