### ISSUE TITLE
[Bug from usability test #1] The user is changing when going on another user profile

### ISSUE THREAD

**Issue by mgpiegette** [scg-unibe-ch/ese2016-team6#62]
1. From the homepage, login with oprah@winfrey.com
2. Go on the ad called "Direkt am Quai: hübsches Studio"
3. In the block "Advertiser", click on "see profile"
4. On the top right, you see that you are registered as John Wayne
5. Then navigate as usual, you are still John Wayne

**Comment by VHaftka** [comment]
Its not changing anymore
