### ISSUE TITLE
[Remark from usability test #1] The user doesn't pay attention to the difference between "for rent", "for sale" and "auction"

### ISSUE THREAD

**Issue by mgpiegette** [scg-unibe-ch/ese2016-team6#64]
When placing an ad, the user doesn't take time to understand the 3 possible deals and the price he must input.

**Comment by mgpiegette** [comment]
Clue : ad a short explaination just above the choice of the type of deal

Proposition : we might remove the choice "auction". Then if you chose "for sale" you can choose "direct" "auction" or "both" (maybe not with radiobutton but with "squares")

**Comment by VHaftka** [comment]
Now there is a visible difference between for rent/for sale/for auction especially for in the price corner, so i would not do something with that...
