### ISSUE TITLE
[Question from usability test #4] How does the data base of registration work ?

### ISSUE THREAD

**Issue by mgpiegette** [scg-unibe-ch/ese2016-team6#75]
1. Signed up as a new user
2. Test made on the site then logged out
3. Pulled from github to get new features
4. Impossible to login with the username & password previously created

Question : does the pulling remove registration information from the database ?

**Comment by mgpiegette** [comment]
Same problem with pages created with these new accounts : they are not displayed anymore

**Comment by VHaftka** [comment]
Yes because they get deleted when you shout down the programm

**Comment by VHaftka** [comment]
and it shout be like that
