### ISSUE TITLE
[Bug from the usability test #4] Impossible to sign up without google account

### ISSUE THREAD

**Issue by mgpiegette** [scg-unibe-ch/ese2016-team6#76]
1. From the homepage, click on "sign up"
2. Fill out the form & validate
3. Site crashes with : 
org.apache.jasper.JasperException: An exception occurred processing JSP page /pages/login.jsp at line 65

62: 	<form:form id="googleForm" type="hidden" class="form-horizontal" method="post"
63: 		modelAttribute="googleForm" action="./googlelogin">
64: 
65: 			<spring:bind path="firstName">
66: 						<form:input type="hidden" path="firstName" cssClass="form-control"
67: 							id="field-firstName" />
68: 			</spring:bind>

**Comment by VHaftka** [comment]
You can now login without login in of the googleLogin
